# Generated by Django 2.2.13 on 2020-06-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('birth_day', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullPictureLocation', models.CharField(max_length=100)),
                ('headPictureLocation', models.CharField(max_length=500)),
                ('encode', models.IntegerField()),
                ('flag', models.CharField(max_length=50)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
    ]
