# Generated by Django 2.2.13 on 2020-06-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200621_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='encode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='flag',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='fullPictureLocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='headPictureLocation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
