# Generated by Django 2.2.13 on 2020-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200621_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fullPictureLocation',
            field=models.ImageField(default='', upload_to='picture/person'),
        ),
    ]
