# Generated by Django 2.2.13 on 2020-06-21 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFound', models.BooleanField(default=False)),
                ('lose_date', models.DateField(default=datetime.datetime(2020, 6, 21, 20, 57, 31, 594462))),
                ('found_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
