# Generated by Django 2.2.13 on 2020-06-21 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_auto_20200621_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='lose_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 21, 37, 34, 857911)),
        ),
    ]
