# Generated by Django 2.2.13 on 2020-06-21 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0003_auto_20200621_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='lose_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 21, 22, 32, 9, 759981)),
        ),
    ]
