# Generated by Django 2.2.13 on 2020-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0002_auto_20200622_1022'),
        ('individual', '0004_auto_20200621_2232'),
    ]

    operations = [
    ]
