# Generated by Django 2.2.13 on 2020-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0009_auto_20200622_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='lose_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
